const INPUT_GROUPS = module.exports = [{
  label: "Branding",
  pattern: /^(brand-|body-bg)/,
}, {
  label: "Fonts",
  pattern: /^(font-|headings-|text-color|link-color|link-hover-color)/
}, {
  label: "State",
  pattern: /^state-/,
}, {
  label: "Buttons",
  pattern: /^btn-/
}, {
  label: "Navbar",
  pattern: /^navbar-/,
}, {
  label: "Alerts",
  pattern: /^alert-/,
}, {
  label: "Inputs",
  pattern: /^(input-|form-|label-)/,
}, {
  label: "Dropdowns",
  pattern: /^(dropdown-)/,
}, {
  label: "Navigation",
  pattern: /^nav-/,
}, {
  label: "Modals",
  pattern: /^modal-/,
}, {
  label: "Tooltips",
  pattern: /^(tooltip-|popover-)/
}, {
  label: "Code",
  pattern: /^(pre-|code-|kbd-)/,
}, {
  label: "Badges",
  pattern: /^badge-/,
}, {
  label: "Breadcrumbs",
  pattern: /^breadcrumb-/,
}, {
  label: "List Groups",
  pattern: /list-group-/,
}, {
  label: "Thumbnails",
  pattern: /^thumbnail-/,
}, {
  label: "Blockquotes",
  pattern: /^blockquote-/
}, {
  label: "Wells",
  pattern: /^well-/,
}, {
  label: "Jumbotron",
  pattern: /jumbotron-/,
}, {
  label: "Tables",
  pattern: /^table-/,
}, {
  label: "Progress Bar",
  pattern: /^progress-/
}, {
  label: "Panel",
  pattern: /^panel-/,
}, {
  label: "Carousel",
  pattern: /^carousel-/,
}, {
  label: "Pagination",
  pattern: /^(pagination-|pager-)/
}, {
  label: "Grays",
  pattern: /^gray/,
}, {
  label: "Sizes",
  pattern: /^(padding-|line-height|border-radius-)/,
}, {
  label: "Z-index",
  pattern: /^zindex/,
}, {
  label: "Grid",
  pattern: /^(screen-|grid-|container-)/,
}]


